/*
 * API na_polya 3.0
 * Все необходимые API для сайта На_поля
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.napolya.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Field
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-22T18:13:14.140549100+03:00[Europe/Moscow]")
public class Field {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private String location;

  public static final String SERIALIZED_NAME_PROVIDER_ID = "provider_id";
  @SerializedName(SERIALIZED_NAME_PROVIDER_ID)
  private Integer providerId;

  public static final String SERIALIZED_NAME_GAMES_IDS = "games_ids";
  @SerializedName(SERIALIZED_NAME_GAMES_IDS)
  private List<Integer> gamesIds = null;


  public Field id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Уникальный идентификатор поля
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "Уникальный идентификатор поля")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Field name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Название поля
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Арена Спорта", required = true, value = "Название поля")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Field description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Описание поля
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Большой стадион с искусственным покрытием для футбольных матчей.", value = "Описание поля")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public Field location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * Местоположение поля
   * @return location
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "ул. Спортивная, д. 1, г. Санкт-Петербург", required = true, value = "Местоположение поля")

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }


  public Field providerId(Integer providerId) {
    
    this.providerId = providerId;
    return this;
  }

   /**
   * id провайдера поля
   * @return providerId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2", required = true, value = "id провайдера поля")

  public Integer getProviderId() {
    return providerId;
  }


  public void setProviderId(Integer providerId) {
    this.providerId = providerId;
  }


  public Field gamesIds(List<Integer> gamesIds) {
    
    this.gamesIds = gamesIds;
    return this;
  }

  public Field addGamesIdsItem(Integer gamesIdsItem) {
    if (this.gamesIds == null) {
      this.gamesIds = new ArrayList<Integer>();
    }
    this.gamesIds.add(gamesIdsItem);
    return this;
  }

   /**
   * id игр, проводимых на этом поле
   * @return gamesIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[101,102,103]", value = "id игр, проводимых на этом поле")

  public List<Integer> getGamesIds() {
    return gamesIds;
  }


  public void setGamesIds(List<Integer> gamesIds) {
    this.gamesIds = gamesIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Field field = (Field) o;
    return Objects.equals(this.id, field.id) &&
        Objects.equals(this.name, field.name) &&
        Objects.equals(this.description, field.description) &&
        Objects.equals(this.location, field.location) &&
        Objects.equals(this.providerId, field.providerId) &&
        Objects.equals(this.gamesIds, field.gamesIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, location, providerId, gamesIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Field {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    gamesIds: ").append(toIndentedString(gamesIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

