/*
 * API na_polya 3.0
 * Все необходимые API для сайта На_поля
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.napolya.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Notification
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-22T18:13:14.140549100+03:00[Europe/Moscow]")
public class Notification {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private String text;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_RECIPIENT_ID = "recipient_id";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_ID)
  private Integer recipientId;

  /**
   * Статус уведомления
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    _("непрочитанное"),
    
    _("прочитанное");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusEnum status;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private OffsetDateTime date;


  public Notification id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Уникальный идентификатор уведомления
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "Уникальный идентификатор уведомления")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Notification text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * Текст уведомления
   * @return text
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Вы записаны в команду A!", required = true, value = "Текст уведомления")

  public String getText() {
    return text;
  }


  public void setText(String text) {
    this.text = text;
  }


  public Notification type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Тип уведомления
   * @return type
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "уведомление о составе команды", required = true, value = "Тип уведомления")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public Notification recipientId(Integer recipientId) {
    
    this.recipientId = recipientId;
    return this;
  }

   /**
   * id получателя уведомления
   * @return recipientId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2", required = true, value = "id получателя уведомления")

  public Integer getRecipientId() {
    return recipientId;
  }


  public void setRecipientId(Integer recipientId) {
    this.recipientId = recipientId;
  }


  public Notification status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Статус уведомления
   * @return status
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "непрочитанное", required = true, value = "Статус уведомления")

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public Notification date(OffsetDateTime date) {
    
    this.date = date;
    return this;
  }

   /**
   * Дата и время отправки уведомления
   * @return date
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2024-11-16T10:00Z", required = true, value = "Дата и время отправки уведомления")

  public OffsetDateTime getDate() {
    return date;
  }


  public void setDate(OffsetDateTime date) {
    this.date = date;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Notification notification = (Notification) o;
    return Objects.equals(this.id, notification.id) &&
        Objects.equals(this.text, notification.text) &&
        Objects.equals(this.type, notification.type) &&
        Objects.equals(this.recipientId, notification.recipientId) &&
        Objects.equals(this.status, notification.status) &&
        Objects.equals(this.date, notification.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, text, type, recipientId, status, date);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Notification {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    recipientId: ").append(toIndentedString(recipientId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

