/*
 * API na_polya 3.0
 * Все необходимые API для сайта На_поля
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.napolya.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;

/**
 * Player
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-22T18:13:14.140549100+03:00[Europe/Moscow]")
public class Player {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SURNAME = "surname";
  @SerializedName(SERIALIZED_NAME_SURNAME)
  private String surname;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  private String role;

  public static final String SERIALIZED_NAME_REGISTRATION_DATE = "registration_date";
  @SerializedName(SERIALIZED_NAME_REGISTRATION_DATE)
  private OffsetDateTime registrationDate;

  public static final String SERIALIZED_NAME_RATING = "rating";
  @SerializedName(SERIALIZED_NAME_RATING)
  private Integer rating;

  public static final String SERIALIZED_NAME_GAMES_IDS = "games_ids";
  @SerializedName(SERIALIZED_NAME_GAMES_IDS)
  private List<Integer> gamesIds = null;

  public static final String SERIALIZED_NAME_ENTRIES_AMOUNT = "entries_amount";
  @SerializedName(SERIALIZED_NAME_ENTRIES_AMOUNT)
  private Integer entriesAmount;


  public Player id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Уникальный идентификатор игрока
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1234", value = "Уникальный идентификатор игрока")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Player name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Имя игрока
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Света", value = "Имя игрока")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Player surname(String surname) {
    
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Багаева", value = "")

  public String getSurname() {
    return surname;
  }


  public void setSurname(String surname) {
    this.surname = surname;
  }


  public Player email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "sveta@gmail.com", value = "")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public Player password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Пароль игрока
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "666#999", value = "Пароль игрока")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  public Player role(String role) {
    
    this.role = role;
    return this;
  }

   /**
   * Роль игрока
   * @return role
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Игрок", value = "Роль игрока")

  public String getRole() {
    return role;
  }


  public void setRole(String role) {
    this.role = role;
  }


  public Player registrationDate(OffsetDateTime registrationDate) {
    
    this.registrationDate = registrationDate;
    return this;
  }

   /**
   * Get registrationDate
   * @return registrationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2024-01-01T12:00Z", value = "")

  public OffsetDateTime getRegistrationDate() {
    return registrationDate;
  }


  public void setRegistrationDate(OffsetDateTime registrationDate) {
    this.registrationDate = registrationDate;
  }


  public Player rating(Integer rating) {
    
    this.rating = rating;
    return this;
  }

   /**
   * Рейтинг игрока
   * @return rating
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "12", value = "Рейтинг игрока")

  public Integer getRating() {
    return rating;
  }


  public void setRating(Integer rating) {
    this.rating = rating;
  }


  public Player gamesIds(List<Integer> gamesIds) {
    
    this.gamesIds = gamesIds;
    return this;
  }

  public Player addGamesIdsItem(Integer gamesIdsItem) {
    if (this.gamesIds == null) {
      this.gamesIds = new ArrayList<Integer>();
    }
    this.gamesIds.add(gamesIdsItem);
    return this;
  }

   /**
   * Список id игр, на которые записан игрок
   * @return gamesIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[2,5,7]", value = "Список id игр, на которые записан игрок")

  public List<Integer> getGamesIds() {
    return gamesIds;
  }


  public void setGamesIds(List<Integer> gamesIds) {
    this.gamesIds = gamesIds;
  }


  public Player entriesAmount(Integer entriesAmount) {
    
    this.entriesAmount = entriesAmount;
    return this;
  }

   /**
   * Количество записей на игры
   * @return entriesAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "3", value = "Количество записей на игры")

  public Integer getEntriesAmount() {
    return entriesAmount;
  }


  public void setEntriesAmount(Integer entriesAmount) {
    this.entriesAmount = entriesAmount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Player player = (Player) o;
    return Objects.equals(this.id, player.id) &&
        Objects.equals(this.name, player.name) &&
        Objects.equals(this.surname, player.surname) &&
        Objects.equals(this.email, player.email) &&
        Objects.equals(this.password, player.password) &&
        Objects.equals(this.role, player.role) &&
        Objects.equals(this.registrationDate, player.registrationDate) &&
        Objects.equals(this.rating, player.rating) &&
        Objects.equals(this.gamesIds, player.gamesIds) &&
        Objects.equals(this.entriesAmount, player.entriesAmount);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, surname, email, password, role, registrationDate, rating, gamesIds, entriesAmount);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Player {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    registrationDate: ").append(toIndentedString(registrationDate)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    gamesIds: ").append(toIndentedString(gamesIds)).append("\n");
    sb.append("    entriesAmount: ").append(toIndentedString(entriesAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

