/*
 * API na_polya 3.0
 * Все необходимые API для сайта На_поля
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.napolya.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Provider
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-22T18:13:14.140549100+03:00[Europe/Moscow]")
public class Provider {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_FIELDS_IDS = "fields_ids";
  @SerializedName(SERIALIZED_NAME_FIELDS_IDS)
  private List<Integer> fieldsIds = null;


  public Provider id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Уникальный идентификатор провайдера
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "Уникальный идентификатор провайдера")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Provider name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Название провайдера
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Поляна", required = true, value = "Название провайдера")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Provider fieldsIds(List<Integer> fieldsIds) {
    
    this.fieldsIds = fieldsIds;
    return this;
  }

  public Provider addFieldsIdsItem(Integer fieldsIdsItem) {
    if (this.fieldsIds == null) {
      this.fieldsIds = new ArrayList<Integer>();
    }
    this.fieldsIds.add(fieldsIdsItem);
    return this;
  }

   /**
   * id полей, которые предоставляет провайдер
   * @return fieldsIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[1,2,3]", value = "id полей, которые предоставляет провайдер")

  public List<Integer> getFieldsIds() {
    return fieldsIds;
  }


  public void setFieldsIds(List<Integer> fieldsIds) {
    this.fieldsIds = fieldsIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Provider provider = (Provider) o;
    return Objects.equals(this.id, provider.id) &&
        Objects.equals(this.name, provider.name) &&
        Objects.equals(this.fieldsIds, provider.fieldsIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, fieldsIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Provider {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    fieldsIds: ").append(toIndentedString(fieldsIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

