/*
 * API na_polya 3.0
 * Все необходимые API для сайта На_поля
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.napolya.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Queue
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-22T18:13:14.140549100+03:00[Europe/Moscow]")
public class Queue {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_PLAYERS_IDS = "players_ids";
  @SerializedName(SERIALIZED_NAME_PLAYERS_IDS)
  private List<Integer> playersIds = new ArrayList<Integer>();

  public static final String SERIALIZED_NAME_GAME_ID = "game_id";
  @SerializedName(SERIALIZED_NAME_GAME_ID)
  private Integer gameId;


  public Queue id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Уникальный идентификатор очереди
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "Уникальный идентификатор очереди")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Queue playersIds(List<Integer> playersIds) {
    
    this.playersIds = playersIds;
    return this;
  }

  public Queue addPlayersIdsItem(Integer playersIdsItem) {
    this.playersIds.add(playersIdsItem);
    return this;
  }

   /**
   * id игроков, находящихся в очереди
   * @return playersIds
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "[5,6,7]", required = true, value = "id игроков, находящихся в очереди")

  public List<Integer> getPlayersIds() {
    return playersIds;
  }


  public void setPlayersIds(List<Integer> playersIds) {
    this.playersIds = playersIds;
  }


  public Queue gameId(Integer gameId) {
    
    this.gameId = gameId;
    return this;
  }

   /**
   * id игры, на которую стоит очередь
   * @return gameId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "id игры, на которую стоит очередь")

  public Integer getGameId() {
    return gameId;
  }


  public void setGameId(Integer gameId) {
    this.gameId = gameId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Queue queue = (Queue) o;
    return Objects.equals(this.id, queue.id) &&
        Objects.equals(this.playersIds, queue.playersIds) &&
        Objects.equals(this.gameId, queue.gameId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, playersIds, gameId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Queue {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    playersIds: ").append(toIndentedString(playersIds)).append("\n");
    sb.append("    gameId: ").append(toIndentedString(gameId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

