/*
 * API na_polya 3.0
 * Все необходимые API для сайта На_поля
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.napolya.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Team
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-22T18:13:14.140549100+03:00[Europe/Moscow]")
public class Team {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PLAYERS_IDS = "players_ids";
  @SerializedName(SERIALIZED_NAME_PLAYERS_IDS)
  private List<Integer> playersIds = null;

  public static final String SERIALIZED_NAME_GAME_ID = "game_id";
  @SerializedName(SERIALIZED_NAME_GAME_ID)
  private Integer gameId;

  public static final String SERIALIZED_NAME_CAPTAIN_ID = "captain_id";
  @SerializedName(SERIALIZED_NAME_CAPTAIN_ID)
  private Integer captainId;


  public Team id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Уникальный идентификатор команды
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "Уникальный идентификатор команды")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public Team name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Название команды
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Команда Победителей", required = true, value = "Название команды")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public Team playersIds(List<Integer> playersIds) {
    
    this.playersIds = playersIds;
    return this;
  }

  public Team addPlayersIdsItem(Integer playersIdsItem) {
    if (this.playersIds == null) {
      this.playersIds = new ArrayList<Integer>();
    }
    this.playersIds.add(playersIdsItem);
    return this;
  }

   /**
   * id игроков, входящих в состав команды
   * @return playersIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[2,3,4]", value = "id игроков, входящих в состав команды")

  public List<Integer> getPlayersIds() {
    return playersIds;
  }


  public void setPlayersIds(List<Integer> playersIds) {
    this.playersIds = playersIds;
  }


  public Team gameId(Integer gameId) {
    
    this.gameId = gameId;
    return this;
  }

   /**
   * id игры, в которой участвует команда
   * @return gameId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "id игры, в которой участвует команда")

  public Integer getGameId() {
    return gameId;
  }


  public void setGameId(Integer gameId) {
    this.gameId = gameId;
  }


  public Team captainId(Integer captainId) {
    
    this.captainId = captainId;
    return this;
  }

   /**
   * id капитана команды
   * @return captainId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2", required = true, value = "id капитана команды")

  public Integer getCaptainId() {
    return captainId;
  }


  public void setCaptainId(Integer captainId) {
    this.captainId = captainId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Team team = (Team) o;
    return Objects.equals(this.id, team.id) &&
        Objects.equals(this.name, team.name) &&
        Objects.equals(this.playersIds, team.playersIds) &&
        Objects.equals(this.gameId, team.gameId) &&
        Objects.equals(this.captainId, team.captainId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, playersIds, gameId, captainId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Team {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    playersIds: ").append(toIndentedString(playersIds)).append("\n");
    sb.append("    gameId: ").append(toIndentedString(gameId)).append("\n");
    sb.append("    captainId: ").append(toIndentedString(captainId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

