/*
 * API na_polya 3.0
 * Все необходимые API для сайта На_поля
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.napolya.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.Field;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FieldApi {
    private ApiClient localVarApiClient;

    public FieldApi() {
        this(Configuration.getDefaultApiClient());
    }

    public FieldApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for fieldsGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Успешный ответ с массивом названий полей </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fieldsGetCall(final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/fields";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fieldsGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        

        okhttp3.Call localVarCall = fieldsGetCall(_callback);
        return localVarCall;

    }

    /**
     * Получить список названий полей
     * 
     * @return List&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Успешный ответ с массивом названий полей </td><td>  -  </td></tr>
     </table>
     */
    public List<String> fieldsGet() throws ApiException {
        ApiResponse<List<String>> localVarResp = fieldsGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Получить список названий полей
     * 
     * @return ApiResponse&lt;List&lt;String&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Успешный ответ с массивом названий полей </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<String>> fieldsGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = fieldsGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Получить список названий полей (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Успешный ответ с массивом названий полей </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fieldsGetAsync(final ApiCallback<List<String>> _callback) throws ApiException {

        okhttp3.Call localVarCall = fieldsGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fieldsIdDelete
     * @param id ID поля (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Поле успешно удалено </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fieldsIdDeleteCall(Integer id, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/fields/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fieldsIdDeleteValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fieldsIdDelete(Async)");
        }
        

        okhttp3.Call localVarCall = fieldsIdDeleteCall(id, _callback);
        return localVarCall;

    }

    /**
     * Удалить поле
     * 
     * @param id ID поля (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Поле успешно удалено </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public void fieldsIdDelete(Integer id) throws ApiException {
        fieldsIdDeleteWithHttpInfo(id);
    }

    /**
     * Удалить поле
     * 
     * @param id ID поля (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Поле успешно удалено </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> fieldsIdDeleteWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = fieldsIdDeleteValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Удалить поле (asynchronously)
     * 
     * @param id ID поля (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Поле успешно удалено </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fieldsIdDeleteAsync(Integer id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = fieldsIdDeleteValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for fieldsIdGet
     * @param id ID поля (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Информация о поле </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fieldsIdGetCall(Integer id, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/fields/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fieldsIdGetValidateBeforeCall(Integer id, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fieldsIdGet(Async)");
        }
        

        okhttp3.Call localVarCall = fieldsIdGetCall(id, _callback);
        return localVarCall;

    }

    /**
     * Получить информацию о поле
     * 
     * @param id ID поля (required)
     * @return Field
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Информация о поле </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public Field fieldsIdGet(Integer id) throws ApiException {
        ApiResponse<Field> localVarResp = fieldsIdGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Получить информацию о поле
     * 
     * @param id ID поля (required)
     * @return ApiResponse&lt;Field&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Информация о поле </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Field> fieldsIdGetWithHttpInfo(Integer id) throws ApiException {
        okhttp3.Call localVarCall = fieldsIdGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<Field>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Получить информацию о поле (asynchronously)
     * 
     * @param id ID поля (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Информация о поле </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fieldsIdGetAsync(Integer id, final ApiCallback<Field> _callback) throws ApiException {

        okhttp3.Call localVarCall = fieldsIdGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<Field>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for fieldsIdPut
     * @param id ID поля (required)
     * @param field  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Поле успешно обновлено </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fieldsIdPutCall(Integer id, Field field, final ApiCallback _callback) throws ApiException {
        Object localVarPostBody = field;

        // create path and map variables
        String localVarPath = "/fields/{id}"
            .replaceAll("\\{" + "id" + "\\}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call fieldsIdPutValidateBeforeCall(Integer id, Field field, final ApiCallback _callback) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling fieldsIdPut(Async)");
        }
        
        // verify the required parameter 'field' is set
        if (field == null) {
            throw new ApiException("Missing the required parameter 'field' when calling fieldsIdPut(Async)");
        }
        

        okhttp3.Call localVarCall = fieldsIdPutCall(id, field, _callback);
        return localVarCall;

    }

    /**
     * Обновить информацию о поле
     * 
     * @param id ID поля (required)
     * @param field  (required)
     * @return Field
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Поле успешно обновлено </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public Field fieldsIdPut(Integer id, Field field) throws ApiException {
        ApiResponse<Field> localVarResp = fieldsIdPutWithHttpInfo(id, field);
        return localVarResp.getData();
    }

    /**
     * Обновить информацию о поле
     * 
     * @param id ID поля (required)
     * @param field  (required)
     * @return ApiResponse&lt;Field&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Поле успешно обновлено </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Field> fieldsIdPutWithHttpInfo(Integer id, Field field) throws ApiException {
        okhttp3.Call localVarCall = fieldsIdPutValidateBeforeCall(id, field, null);
        Type localVarReturnType = new TypeToken<Field>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Обновить информацию о поле (asynchronously)
     * 
     * @param id ID поля (required)
     * @param field  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Поле успешно обновлено </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Поле не найдено </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call fieldsIdPutAsync(Integer id, Field field, final ApiCallback<Field> _callback) throws ApiException {

        okhttp3.Call localVarCall = fieldsIdPutValidateBeforeCall(id, field, _callback);
        Type localVarReturnType = new TypeToken<Field>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
