/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.napolya.controller;

import com.example.napolya.model.Notification;
import jakarta.annotation.Generated;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.List;
import java.util.Optional;

public interface NotificationsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /notifications : Получить список id уведомлений
     *
     * @return Успешный ответ с массивом id уведомлений (status code 200)
     */
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/notifications",
            produces = {"application/json"}
    )
    default ResponseEntity<List<Integer>> notificationsGet() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "0";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * DELETE /notifications/{id} : Удалить уведомление
     *
     * @param id ID уведомления (required)
     * @return Уведомление успешно удалено (status code 204)
     * or Уведомление не найдено (status code 404)
     */
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = "/notifications/{id}"
    )
    default ResponseEntity<Void> notificationsIdDelete(@PathVariable("id") Integer id) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * GET /notifications/{id} : Получить информацию об уведомлении
     *
     * @param id ID уведомления (required)
     * @return Информация об уведомлении (status code 200)
     * or Уведомление не найдено (status code 404)
     */
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/notifications/{id}",
            produces = {"application/json"}
    )
    default ResponseEntity<Notification> notificationsIdGet(@PathVariable("id") Integer id) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"2024-11-16T10:00:00Z\", \"id\" : 1, \"text\" : \"Вы записаны в команду A!\", \"type\" : \"уведомление о составе команды\", \"recipient_id\" : 2, \"status\" : \"непрочитанное\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * PUT /notifications/{id} : Обновить информацию об уведомлении
     *
     * @param id ID уведомления (required)
     * @param notification (required)
     * @return Уведомление успешно обновлено (status code 200)
     * or Уведомление не найдено (status code 404)
     */
    @RequestMapping(
            method = RequestMethod.PUT,
            value = "/notifications/{id}",
            produces = {"application/json"},
            consumes = {"application/json"}
    )
    default ResponseEntity<Notification> notificationsIdPut(@PathVariable("id") Integer id, @RequestBody Notification notification) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"2024-11-16T10:00:00Z\", \"id\" : 1, \"text\" : \"Вы записаны в команду A!\", \"type\" : \"уведомление о составе команды\", \"recipient_id\" : 2, \"status\" : \"непрочитанное\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

    /**
     * POST /notifications : Создать новое уведомление
     *
     * @param notification (required)
     * @return Уведомление успешно создано (status code 201)
     */
    @RequestMapping(
            method = RequestMethod.POST,
            value = "/notifications",
            produces = {"application/json"},
            consumes = {"application/json"}
    )
    default ResponseEntity<Notification> notificationsPost(@RequestBody Notification notification) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"date\" : \"2024-11-16T10:00:00Z\", \"id\" : 1, \"text\" : \"Вы записаны в команду A!\", \"type\" : \"уведомление о составе команды\", \"recipient_id\" : 2, \"status\" : \"непрочитанное\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}

