/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.napolya.controller;

import com.example.napolya.model.InlineResponse200;
import jakarta.annotation.Generated;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.List;
import java.util.Optional;

public interface PhotosApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /photos : Получение списка фотографий
     * Возвращает список фотографий для отображения на главной странице.
     *
     * @return Успешный ответ с списком фотографий (status code 200)
     */
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/photos",
            produces = {"application/json"}
    )
    default ResponseEntity<List<InlineResponse200>> photosGet() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"created_at\" : \"2024-04-01T15:00:00Z\", \"description\" : \"Описание фотографии\", \"id\" : 1, \"url\" : \"https://example.com/photo1.jpg\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
}
